[tools]
bun = "1.3.4"

[tasks.lint]
description = "Lint the code"
run = "bun lint"

[tasks.dev]
description = "Run the development server"
run = "bun dev"

[tasks.test]
description = "Run the tests"
run = "bun run test"

[tasks.build]
description = "Build the project"
run = "bun run build"